import test from 'node:test';
import assert from 'node:assert/strict';
import {SAMPLE,validate,assess,prepareDraft,exportReport} from '../src/engine.js';
test('validates people boundaries and package threshold',()=>{for(const [employees,price] of [[5,790],[10,790],[11,1490],[25,1490]]) assert.equal(assess({...SAMPLE,employees}).plan.price,price);for(const employees of [4,26,NaN,Infinity,5.5,'8',null]) assert.throws(()=>validate({...SAMPLE,employees}));});
test('rejects missing, extra, malformed and adversarial inputs',()=>{for(const input of [null,[],{...SAMPLE,backup:'<script>'},{...SAMPLE,password:'secret'},{...SAMPLE,revenue:-1},{...SAMPLE,hours:73},{...SAMPLE,partner:'attacker'}]) assert.throws(()=>validate(input)); const x={...SAMPLE};delete x.backup;assert.throws(()=>validate(x));});
test('money is scenario arithmetic, handles zero income',()=>{const a=assess(SAMPLE);assert.equal(a.exposure,8000);assert.equal(a.equivalentHours,.79);const b=assess({...SAMPLE,revenue:0});assert.equal(b.equivalentHours,null);assert.equal(b.exposure,0);});
test('unknown does not become safe; incident overrides all protections',()=>{assert.ok(assess(SAMPLE).humanRequired);const a=assess({...SAMPLE,backup:'yes',access:'yes',updates:'yes',incident:'yes'});assert.equal(a.severity,'Atención inmediata');assert.equal(a.actions[0].id,'incident');});
test('all 54 control combinations yield exactly three unique priorities',()=>{for(const backup of ['yes','no','unknown'])for(const access of ['yes','no','unknown'])for(const updates of ['yes','no','unknown'])for(const incident of ['yes','no']) {const a=assess({...SAMPLE,backup,access,updates,incident});assert.equal(a.actions.length,3);assert.equal(new Set(a.actions.map(x=>x.id)).size,3);}});
test('approval is explicit and export stays labeled',()=>{const a=assess(SAMPLE);for(const x of [false,undefined,'true',1])assert.throws(()=>prepareDraft(a,x));const d=prepareDraft(a,true);assert.equal(d.type,'Borrador local; no enviado');assert.equal(exportReport(a,[],d).demo,true);});
